# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  namespace: devops-app
  labels:
    app: devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      serviceAccountName: devops-app-sa
      containers:
        - name: api
          image: your-registry.io/your-org/devops-app:TAG
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: devops-app-config
                  key: APP_ENV
            - name: APP_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: devops-app-config
                  key: APP_LOG_LEVEL
            - name: APP_PORT
              value: '8080'
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: devops-app-secret
                  key: DB_URL
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: '100m'
              memory: '128Mi'
            limits:
              cpu: '500m'
              memory: '512Mi'
