# k8s/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devops-app-role
  namespace: devops-app
rules:
  - apiGroups: ['']
    resources: ['pods', 'configmaps', 'secrets']
    verbs: ['get', 'list']
